### ISSUE TITLE
Graph shall deliver historical balances

### ISSUE THREAD

**Issue by 5-mark** [playzero/zero-network#202]
## User Story
As user I want to see the current and historical token balances of a DAO treasury so I can get insights about their wealth development. In order to enable Frontend to build it we need a Graph update. 

## Acceptance Criteria

1. **History:** Graph should be queryable for: blocknumber[], wallet address, currencyID & balance
2. **Latest:** Graph should be queryable for: wallet address, currencyID & balance

## Additional Information

- is blocking frontend ticket https://github.com/gamedaoco/gamedao-haiku/issues/310

## How to test

1. open graph and find balance queries and submit: blocknumber or range of blocknumber for a given wallet address and currencyID to retrieve balances
3. check current balance with subscribing to the current balance

**Comment by vovacha** [comment]
We've already discussed a number of different approaches in the scope of this task, but the final one is next:

- iterate over blocks
- read Balances and Token related events from every block
- get balance data directly from the chain's storage for each account mentioned in the block's events

I think the best would be to utilize Subsquid and not implement a new service (reuse ORML, DB, blocks processing logic).

With the old Subsquid's processor implementation, I'm struggling of finding a way to iterate over blocks. [With the newest Subsquid it's possible.](https://github.com/subsquid/squid-substrate-template/blob/main/src/processor.ts#L88)

Since the migration to Firesquid was still one of our high-priority tasks, my suggestion would be to do #160 first and then switch to this task.

@2075 does it make sense to you?
cc: @5-mark @vayesy

**Comment by 2075** [comment]
@vovacha ACK. ETA?

**Comment by vovacha** [comment]
#160 - the main complexity there - is a new batch processor implementation. It looks more like 3 SP, but there is some uncertainty (1-3 days).
#202 (current) - 3 SP (~2 days).

Ok, I'm switching immediately to the #160 then.

**Comment by 2075** [comment]
@vovacha what is the status here?

**Comment by vovacha** [comment]
Done. Test env: [https://test.graph.dev.sub.zero.io/](https://test.graph.dev.sub.zero.io/)
